-- 1. EJZ274: RETURNS EMPLOYEE CONTANCT INFO ORDERED BY LAST NAME IN ASCENDING SEQUENCE
SELECT FIRST_NAME, LAST_NAME, EMAIL, PRIMARY_PHONE
FROM PASSENGER
ORDER BY LAST_NAME ASC;

-- 2. EJZ274: RETURNS PASSENGER FULL NAME FOR INDIVIDUALS WHOSE LAST NAME BEGINS W/ FIRST 3 LETTERS OF ALPHABET
SELECT FIRST_NAME ||' '|| LAST_NAME AS PASSENGER_FULL_NAME
FROM PASSENGER
WHERE SUBSTR(LAST_NAME,1,1) IN ('A','B','C')
ORDER BY FIRST_NAME ASC;

-- 3. EJZ274: RETURNS EMPLOYEE INFORMATION FOR INDIVIDUALS WHOSE BIRTHDATE BETWEEN JAN'70 AND DEC'79
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, MAILING_ADDRESS
FROM EMPLOYEE
WHERE BIRTHDAY > '01-JAN-70' AND BIRTHDAY <= '31-DEC-79'
ORDER BY BIRTHDAY DESC;

-- 4. EJZ274: DUPLICATE QUERY OF #3 BUT USES BETWEEM OPERATOR 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, MAILING_ADDRESS
FROM EMPLOYEE
WHERE BIRTHDAY BETWEEN '01-JAN-70' AND '31-DEC-79'
ORDER BY BIRTHDAY DESC;

-- 5. EJZ275: RETURNS FREQUENT FLYER PROFILE INFO AND FREE FLIGHT INFO
SELECT PASSENGER_ID, FREQUENT_FLYER_ID, FF_LEVEL AS STATUS, MILES_BALANCE AS MILES_EARNED, TRUNC(MILES_BALANCE/12500) AS FREE_FLIGHTS
FROM FREQUENT_FLYER_PROFILE
WHERE ROWNUM <= 8
ORDER BY MILES_EARNED DESC;

-- 6. EJZ274: RETURNS FREQUENT FLYER PROFILE FOR THOSE WHO HAVE EARNED MORE THATN 4 FOOD VOUCHERS
SELECT PASSENGER_ID, FREQUENT_FLYER_ID, FF_LEVEL AS STATUS_LEVEL, MILES_BALANCE AS BALANCE
FROM FREQUENT_FLYER_PROFILE
WHERE TRUNC((MILES_BALANCE - 5000)/10000) > 4;

-- 7. EJZ274: RETURNS PASSENGER INFO OF THOSE WITH MAILING ADDRESS 2
SELECT FIRST_NAME, LAST_NAME, MAILING_ADDRESS_1, MAILING_ADDRESS_2, MAILING_STATE, MAILING_ZIP
FROM PASSENGER
WHERE MAILING_ADDRESS_2 IS NOT NULL
ORDER BY LAST_NAME;

--8. EJZ274: RETURNS DATE AND TAX RATE INFORMATION 
SELECT SYSDATE AS TODAY_UNFORMATTED, TO_CHAR(SYSDATE,'MM/DD/YYYY') AS TODAY_FORMATTED, 100 AS PRICE,.0825 AS TAX_RATE, 
100*.0825 AS TAX_SUM, 100 + (100*.0825) AS FINAL_TOTAL 
FROM DUAL;

-- 9. EJZ274: RETRIEVES THE TOP 5 FREQUENT FLYER PROFILES WITH HIGHEST MILES BALANCE
SELECT PASSENGER_ID, FREQUENT_FLYER_ID, FF_LEVEL, MILES_BALANCE
FROM FREQUENT_FLYER_PROFILE
ORDER BY MILES_BALANCE DESC
FETCH FIRST 5 ROWS ONLY;

-- 10. EJZ274: JOINS PASSENGER TABLE TO FF TABLE TO RETURN FREQUENT FLYER PROFILE
SELECT FF_LEVEL AS STATUS, FIRST_NAME, LAST_NAME
FROM FREQUENT_FLYER_PROFILE FF_P
    JOIN PASSENGER P ON FF_P.PASSENGER_ID = P.PASSENGER_ID
ORDER BY MILES_BALANCE DESC;

-- 11. EJZ274: RETURN PASSENGER AND RESERVATION INFO OF A PASSENGER USING MULTIPLE JOINS
SELECT R.RESERVATION_ID, FIRST_NAME ||' '|| MIDDLE_NAME||' '|| LAST_NAME AS PASSENGER_NAME, FLIGHT_ID, SEAT_ASSIGNMENT
FROM PASSENGER P
    JOIN PASS_RESV_FLIGHT_LINKING PRFL ON P.PASSENGER_ID = PRFL.PASSENGER_ID
    JOIN RESERVATION R ON PRFL.RESERVATION_ID = R.RESERVATION_ID
WHERE EMAIL = 'meredithburrel@pmail.com';

-- 12. EJZ274: RETURN FLIGHT AND PASSENGER INFO FOR FLIGHT 44 USING JOIN
SELECT DEPARTURE_CITY, ARRIVAL_CITY, FIRST_NAME, LAST_NAME, SEAT_ASSIGNMENT, CHECKED_IN_FLAG
FROM FLIGHT F
    JOIN PASS_RESV_FLIGHT_LINKING PRFL ON F.FLIGHT_ID = PRFL.FLIGHT_ID
    JOIN PASSENGER P ON PRFL.PASSENGER_ID = P.PASSENGER_ID
WHERE F.FLIGHT_ID = 44
ORDER BY LAST_NAME;

-- 13. EJZ274: RETURNS PASSENGERS THAT HAVE NOT HAD A FLIGHT RESERVATION YET USING OUTER JOIN
SELECT DISTINCT FIRST_NAME, LAST_NAME, P.EMAIL
FROM PASSENGER P
    LEFT JOIN PASS_RESV_FLIGHT_LINKING PRFL ON P.PASSENGER_ID = PRFL.PASSENGER_ID
WHERE RESERVATION_ID IS NULL
ORDER BY P.LAST_NAME;

-- 14. EJZ274: RETURN FREQUENT FLYER PROFILE USING UNION
SELECT '1-TOP-TIER' AS PASSENGER_TIER, FREQUENT_FLYER_ID, FF_LEVEL, MILES_BALANCE
FROM FREQUENT_FLYER_PROFILE
WHERE MILES_BALANCE > 75000
    UNION
SELECT '2-MID-TIER' AS PASSENGER_TIER, FREQUENT_FLYER_ID, FF_LEVEL, MILES_BALANCE
FROM FREQUENT_FLYER_PROFILE
WHERE MILES_BALANCE BETWEEN 25000 AND 75000
    UNION
SELECT '3-LOW-TIER' AS PASSENGER_TIER, FREQUENT_FLYER_ID, FF_LEVEL, MILES_BALANCE
FROM FREQUENT_FLYER_PROFILE
WHERE MILES_BALANCE < 25000
ORDER BY MILES_BALANCE DESC


